name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          global-json-file: ./global.json
      - name: Run Test
        run: |
          if [ "$RUNNER_OS"  == "Windows"]: then
            dotnet test ./src/nunit.analyzers.tests/
          else
            dotnet test -f net6.0 ./src/nunit.analyzers.tests/
          fi
