name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          global-json-file: ./global.json
      - name: .NET6.0 Test
        run: |
            dotnet test -f net6.0 ./src/nunit.analyzers.tests/

      - name: .NET Framework Test
        if: runner.os == 'Windows'
        run: |
            dotnet tool restore
            dotnet test --collect:"" -f net462 ./src/nunit.analyzers.tests/
            dotnet dotnet-coverage merge -o merged.cobertura.xml -f cobertura -r coverage.cobertura.xml

      - name: Post Coverage
        uses: k1LoW/octocov-action@v0
        if: runner.os == 'Windows'
