name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          global-json-file: ./global.json
      - name: .NET6.0 Test
        run: |
            dotnet test -f net6.0 ./src/nunit.analyzers.tests/

      - name: .NET Framework Test
        if: runner.os == 'Windows'
        run: |
            dotnet test -f net462 ./src/nunit.analyzers.test
