name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          global-json-file: ./global.json
      - name: dotnet test
        run: dotnet test ./src/nunit.analyzers.tests/
